site_name: Amit Kumar
site_description: "Engineer by profession, Leader by choice"
site_url: "https://amitkmr.github.io"
copyright: "Copyright &copy; 2023 Amit Kumar"
docs_dir: docs/
# plugins:
#   - blog
markdown_extensions:
  - md_in_html
  - attr_list
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  icon:
    logo: material/book
  palette:
    primary: white
  font:
    text: Rubik
  features:
    - tabs
    - instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
nav:
  - Hi There: index.md
  - Overview: overview.md
  - Bookshelf: bookshelf.md
