site_name: Amit Kumar
site_description: "Engineer by profession, Leader by choice"
site_url: "https://amitkmr.github.io"
copyright: "Copyright &copy; 2023 Amit Kumar"
docs_dir: docs/
# plugins:
#   - blog
theme:
  name: material
  palette:
    primary: white
  features:
    - tabs
    - instant
    - navigation.tabs
nav:
  - About: index.md
  - Now: now.md
  - Blog:
    - blog/index.md
    - 2023:
        - blog/posts/why-personal-website.md
