site_name: Amit Kumar
site_description: "Engineer by profession, Leader by choice"
site_url: "https://amitkmr.github.io"
copyright: "Copyright &copy; 2023 Amit Kumar"
docs_dir: docs/
repo_name: 'amitkmr/personal-website'
repo_url: 'https://github.com/amitkmr/personal-website'
extra:
  analytics:
    provider: google
    property: G-7S4JR3KFHK
theme:
  name: material
  palette:
    primary: white
  features:
    - tabs
    - instant
    - navigation.tabs
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Home: about.md
  - Now: now.md
  # - Blogs:
  #     - blogs/high-growth-year.md
