site_name: Amit Kumar
site_description: "Engineer by profession, Leader by choice"
site_url: "https://amitkmr.github.io"
copyright: "Copyright &copy; 2023 Amit Kumar"
docs_dir: docs/
# plugins:
#   - blog
theme:
  name: material
  icon:
    logo: material/book
  palette:
    primary: white
  font:
    text: Rubik
  features:
    - tabs
    - instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
nav:
  - About: index.md
  - Now: now.md
  - Blog:
    - blog/posts/why-personal-website.md
  - Books:
    - Startup:
        - books/startup/the_founders_dilemmas.md
        - books/startup/the_mom_test.md
    - Wealth & Happiness:
        - books/wealth_and_happiness/the_almanack_of_naval_ravikant.md
